### ISSUE TITLE
couple of questions

### ISSUE THREAD

**Issue by blastik** [angrychimp/ansible-module-dynamodb-scan#1]
hi there,
i came across to your plugin and wanted to ask you a couple of things:
1. i guess you are not able to deal with profiles into the aws credentials file
2. wouldn't make more sense to do a lookup plugin instead?

regards,
d.

**Comment by blastik** [comment]
i'll make it compatible with aws profiles. do you want a PR ?

**Comment by angrychimp** [comment]
So I _thought_ it would work with profiles as I borrowed quite a bit from some of the existing AWS plugins. I know for certain that it'll respect profiles set in the AWS_PROFILE environment variable, but if it isn't working for your use case I'll absolutely accept a PR.

As for a lookup plugin (I'm assuming you mean a "query" as opposed to a "scan") - the tables I was working with weren't large enough to make much a difference and some of what I was doing (storing configuration options in a table) lent more toward a scan than a query. But I certainly recognized there would be a host of use cases where a query would be more useful.

If you'd like I can go back an draft a separate `dynamodb_query_table_facts` plugin that would do just that.
